# gpSP makefile
# Gilead Kutnick - Exophase

# Global definitions

CC        = x86_64-w64-mingw32-gcc
OBJS      = main.o
BIN       ?= bittboy.exe

# Platform specific definitions 

VPATH      += ..
CFLAGS     += -O2 -g
INCLUDES   = -I.
LIBS       = -static -lgcc

# Compilation:

all:	${BIN}

%.o: %.c
	${CC} ${CFLAGS} ${INCLUDES} -c -o $@ $<

${BIN}:	${OBJS}
	${CC} ${OBJS} ${LIBS} -o ${BIN}  

clean:
	rm -f *.o ${BIN} 

